### ISSUE TITLE
need help setting up on arm/v7 rpi 3b+

### ISSUE THREAD

**Issue by VooDisss** [ChatDeBlofeld/seafile-arm-docker-base#19]
Hello, i tryed 1-2 days to set it up, and cannot, need help cause i have no more energy trying by myself, heres my reddit post:
https://www.reddit.com/r/selfhosted/comments/qhyenc/need_help_setting_up_seafile/

**Comment by ChatDeBlofeld** [comment]
Can you run the following command and paste the result here?

```
docker exec <name_or_id_of_the_swag_container> cat /config/nginx/site-confs/seafile.conf
```

**Comment by ChatDeBlofeld** [comment]
Closed because author [installed Nextcloud instead](https://github.com/haiwen/seafile-rpi/issues/92), no idea if this came from a bug or a bad configuration.

**Comment by VooDisss** [comment]
I can just show you all the steps i do if you dont believe me... the seahub server does not start, i got to a point i dont get any errors in the terminal (maybe they are in the logs but idk where are they for further troubleshooting). 
I was using this repository: 
https://github.com/haiwen/seafile-rpi
and used this one earlier without success on a clean install of raspbian with some extra things that are mentioned to be needed in the documentation:
https://github.com/ChatDeBlofeld/seafile-arm-docker-base

The ./seafile.sh start command starts, but ./seahub.sh start does not

**Comment by ChatDeBlofeld** [comment]
> I was not installing using docker, as @ChatDeBlofeld expects i guess

This is quite confusing to hear on a Docker image repository... Thus your error is normal since the compose topology you took from my other repo isn't configured to work with Seafile installed on the host.

**Comment by VooDisss** [comment]
What i mean was that i tryed both the docker compose method of installing
seafile and building the image (another repository i mentioned) both stuck
at seafile server either not starting or showing "welcome to your swag
instance" instead of first login page

**Comment by ChatDeBlofeld** [comment]
OK, eventually I understand. Then if you want to go on with Seafile and the Docker way, I need more information. 

### 1. Cleaning

Uninstall both Apache and Nginx from your host to ensure they're not taking precedence:

```
sudo apt remove nginx apache2
```

Remove the current container:

```
sudo ./compose.sh down -v
```

### 2. Log stuff

Execute:

```
sudo ./compose.sh up
```

When it stops displaying stuff, **copy-paste the result here** and stop the container by hitting `CTRL+C`.

**Copy the content of all files** in the `/media/hdd/seafile/logs` folder too.


### 3. Check configuration

Rerun your containers in detached mode:

```
sudo ./compose.sh up -d
```

**Run the following and copy-paste the result:**

```
sudo docker exec seafile-arm-docker_reverse-proxy_1 cat /config/nginx/site-confs/seafile.conf
```
