### ISSUE TITLE
Symbolic link loop for avatars/

### ISSUE THREAD

**Issue by kevinxw** [ChatDeBlofeld/seafile-arm-docker-base#2]
The image was created with symbolic link loop for avatars/ folder

```
/opt/seafile# ls /shared/media/avatars
ls: cannot access '/shared/media/avatars': Too many levels of symbolic links
```

```
root@4454eb18a360:/opt/seafile# ls /shared/media/avatars -al
lrwxrwxrwx 1 seafile seafile 22 Mar 10 10:46 /shared/media/avatars -> ../seahub-data/avatars
root@4454eb18a360:/opt/seafile# ls /shared/media/custom -al
lrwxrwxrwx 1 seafile seafile 21 Mar 10 10:29 /shared/media/custom -> ../seahub-data/custom
```

Use absolute path should resolve the problem.

**Comment by ChatDeBlofeld** [comment]
Hi,
 
This is something happening when Seafile is reinstalled without cleaning the old media folder, this should not appears with empty volumes. I will look if I can add a safeguard against this.

If you think this is unrelated, please provide your full `run` command so I can look further.

**Comment by kevinxw** [comment]
I think you are right. I used docker compose and created the named volume for media. I did not explicitly remove that named volume during reinstall.
Could you add a check that if such folder exist, clean it up or reuse it?
