### ISSUE TITLE
deprecated getiterator removed in Python3.9

### ISSUE THREAD

**Issue by jkumeboshi** [ChatDeBlofeld/seafile-arm-docker-base#21]
WOPI handler stopped working with Python3.9

this commit fix the WOPI handler:
https://github.com/haiwen/seahub/commit/30914eff0c4e4fbda2b77a7b7f8ac1a9b96b4172

**Comment by ChatDeBlofeld** [comment]
Hi,

Thx for reporting, this will be automatically fixed with the image release for Seafile 9 which, I hope, will be available soon.
