### ISSUE TITLE
Missing dependencies for memcached, moviepy etc

### ISSUE THREAD

**Issue by kevinxw** [ChatDeBlofeld/seafile-arm-docker-base#3]
The dependencies for memcached (django_pylibmc / pylibmc etc) and video thumbnail generation (pillow / moviepy etc) are missing. It would be great if these can be added.

```
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_pylibmc.memcached.PyLibMCCache': No module named 'django_pylibmc'
2021-03-10 22:41:13,777 [ERROR] seahub.thumbnail.utils:34 <module> Could not find moviepy installed.
```

**Comment by ChatDeBlofeld** [comment]
A fix for the memcached dependencies has been pushed on [a new branch](https://github.com/ChatDeBlofeld/seafile-arm-docker-base/tree/fb-memcached), should work but not really tested though. If you can confirm it's ok (`./build-image.sh -t memcached -l amd64` or something like that to create a testing image for your local machine, see build instructions) I will merge and build the image for the hub.

For the thumbnails there is two problems:
- After installing the dependencies the image was broken, quite annoying
- It seems to increase the image size a lot (x2), this is not something wanted and could be a blocking problem

I'll see what I can do about that over the weekend.

**Comment by kevinxw** [comment]
The branch doesn’t work. Complaining about missing python3.
I am tweaking it on my side and see if I can get it work.

**Comment by ChatDeBlofeld** [comment]
This is unexpected. Build's working fine for amd64 but fails for arm, because we all like consistency...

This is probably some missing dependencies in the arm images (always is...), I'll quickly look if can I can do something about it.

**Comment by ChatDeBlofeld** [comment]
Should now work fine (arm64 at least, will test arm/v7 later).

Added the following to the compose file:

```
memcached:
    image: memcached
```

And in seahub_settings.py:

```
CACHES = {
    'default': {
        'BACKEND': 'django_pylibmc.memcached.PyLibMCCache',
        'LOCATION': 'memcached:11211',
    },
}
```
And everything ran without crashing. :+1: 

I will probably test a bit more and push the hub this afternoon.

**Comment by kevinxw** [comment]
Thanks for your work!

**Comment by ChatDeBlofeld** [comment]
So I've had a look at what you did on your side and what it implies to support thumbnails. As you probably expect dependencies are too heavy for me given the functionality so I won't add them, sorry.

**Comment by kevinxw** [comment]
No problem. Thanks for the effort.
