### ISSUE TITLE
License

### ISSUE THREAD

**Issue by olof-nord** [ChatDeBlofeld/seafile-arm-docker-base#31]
Which license is applicable/wished for the source code in this repository?

There are a few different licenses to choose from for a community-oriented project, but clarifying this might be a good idea.

https://choosealicense.com/

**Comment by ChatDeBlofeld** [comment]
Never cared about that but it would be necessary indeed...

Will check how to add a MIT or Apache license properly, given that there's Seahub code in the `custom` directory.

**Comment by ChatDeBlofeld** [comment]
Licensed under Apache 2.0
