### ISSUE TITLE
Add environment variable for memcached

### ISSUE THREAD

**Issue by ChatDeBlofeld** [ChatDeBlofeld/seafile-arm-docker-base#40]
- [ ] Environment variable
- [ ] Tests. Either write a new test scenario, which will extend test duration probably unnecessary, or activate for all scenarios and assume if it works with memcached, it works without.

**Comment by olof-nord** [comment]
+1 for this, I have been wondering for a while if my memcached instance is actually used.
How can one verify that Seafile is actually using it? (either manually, or preferreably per script/cli)

**Comment by ChatDeBlofeld** [comment]
With memcached enabled and no log in `logs/seahub.log` stating there is an issue with memcached, I think you can assume Seahub is using it.

A more reliable but less cli-compliant way would be to enable memcached logs with the second level of verbosity. In a compose file, that means to add a `command` property:

```yaml
memcached:
  image: memcached
  command: ["-vv"]
  # ...

Then browsing Seahub while `docker logs -f <name>` should show a ton of operations.
